### ISSUE TITLE
How can I get host header value

### ISSUE THREAD

**Issue by subi-kp** [jhuckaby/pixl-request#2]
As this is the request module used in chronicle, if i can get a host header value from this module, then I can able to use this module for developing application over the proxy or loadbalancer

**Comment by jhuckaby** [comment]
This module is used for *sending* HTTP requests, not receiving them.  It is similar to [request](https://www.npmjs.com/package/request), [superagent](https://www.npmjs.com/package/superagent) or [got](https://www.npmjs.com/package/got).  It is an "**HTTP Client**" library or "**User Agent**" which issues requests to a target URL.  So in the context of this module, to answer your question, the `Host` header is whatever *you yourself passed in on the URL*, when making a request.

I think perhaps this issue was logged in the wrong repository.  Did you perhaps mean to enter this issue into my [pixl-server-web](https://github.com/jhuckaby/pixl-server-web) web server module?  Cronicle uses that too.  That is a "web server" (similar to [express](https://www.npmjs.com/package/express)) and actually *receives incoming HTTP requests*.  In the context of *that* module, you can retrieve the `Host` HTTP request header by `args.request.headers.host`. See [args.request](https://github.com/jhuckaby/pixl-server-web#argsrequest).

**Comment by subi-kp** [comment]
Got it. Wrong repo, hence closing the issue.
